CostPredictor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('carpredictor.urls')),
    path('admin/', admin.site.urls),
]

carpredictor/urls.py
from django.urls import path
from . import views

app_name = 'carpredictor'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('CarList/', views.CarList.as_view(), name='CarList'),
    path('carpredictor/ExtendsCarData', views.GetCarData, name='GetCarData'),
]

carpredictor/models.py
from django.db import models
from datetime import date

# Create your models here.
class Car(models.Model):
    name = models.CharField("مدل ماشین", max_length = 100)
    year = models.CharField("سال تولید", max_length = 50)
    description = models.CharField("توضیحات", max_length = 200)
    km = models.CharField("کارکرد", max_length = 50)
    price = models.CharField("قیمت", max_length = 50)
    created = models.DateField("تاریخ", default=date.today(), blank=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return f'{self.name}-{self.year}-{self.km}-{self.created}'

carpredictor/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.views import generic
from django.urls import reverse
from .models import Car
from . import readcar

def home(request):
    return render(request, 'carpredictor/index.html')

class CarList(generic.ListView):
    template_name = 'carpredictor/carlist.html'
    context_object_name = 'car_list'
    paginate_by = 100

    def get_queryset(self):
        car_list = Car.objects.order_by('created')
        return car_list

def GetCarData(request):
    car_list = readcar.read_data()
    for car in car_list:
        q = Car(
            name = car.name,
            year = car.year,
            description = car.description,
            km = car.km,
            price = car.price,
        )
        q.save()
    return render(request, "carpredictor/confirm.html")

carpredictor/templates/carpredictor/carlist.html
{% extends 'carpredictor/master.html' %}

{% block title %}
List of Cars
{% endblock %}

{% block content %}
<h1 class=".container-fluid text-center pt-5">List of Cars</h1>
<div class="text-center">
    <a class="btn btn-success" href = "{% url 'carpredictor:GetCarData' %}" role="button">Get More Data</a><br>
</div>
<h4 class=".container-fluid text-center pt-5">Cars List:</h4>

<table class="table table-striped table-bordered text-center">
    <tr class="table-dark">
        <th>مدل ماشین</th>
        <th>توضیحات</th>
        <th>سال تولید</th>
        <th>کارکرد</th>
        <th>(تومان) قیمت</th>
        <th>تاریخ</th>
    </tr>
    {% for car in car_list %}
    <tr>
        <td>{{car.name}}</td>
        <td>{{car.description}}</td>
        <td>{{car.year}}</td>
        <td>{{car.km}}</td>
        <td>{{car.price}}</td>
        <td>{{car.created}}</td>
    </tr>
    {% endfor %}
</table>

<div class="pagination">
    <li class="step-links">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}

        <span class="current page-link active">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
    </span>
</div>
{% endblock %}

carpredictor/templates/carpredictor/confirm.html
{% extends 'carpredictor/master.html' %}

{% block title %}
Confirmed
{% endblock %}

{% block content %}
<h1 class="container p-5 my-5 text-bg-warning text-white">Data Extracted Successfully</h1>
{% endblock %}

carpredictor/templates/carpredictor/index.html
{% extends 'carpredictor/master.html' %}

{% block title %}
Home Page
{% endblock %}

{% block content %}
<h2 class="container-sm p-5 my-5 rounded border text-center text-bg-secondary">Welcome to Cost Predictor</h2>
<div class="mt-4 p-5 bg-success text-white">
    <h3>Categories:</h3>
    <ul>
        <li><a class="alert-link" href = #>Cars Cost Predictor</a></li>
    </ul>
</div>
{% endblock %}

carpredictor/templates/carpredictor/master.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <h1 class="container-fluid p-5 bg-primary text-white text-center">Cost Predictor</h1>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid justify-content-center">
      <ul class="navbar-nav nav-pills">
        <li class="nav-item"><a class="nav-link" href = "{% url 'carpredictor:home' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link" href = "{% url 'carpredictor:CarList' %}">Cars List</a></li>
      </ul>
    </div>
  </nav>
{% block content %}
{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>